# Generated by Django 2.0 on 2017-12-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pixcel_table',
            new_name='pixel_table',
        ),
    ]
