# Generated by Django 2.0 on 2017-12-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171226_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel_table',
            name='reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
