# Generated by Django 2.0 on 2017-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('Owner', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('KRW', models.DecimalField(decimal_places=0, max_digits=20)),
                ('BTC', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ETH', models.DecimalField(decimal_places=8, max_digits=20)),
                ('BCH', models.DecimalField(decimal_places=8, max_digits=20)),
                ('XRP', models.DecimalField(decimal_places=8, max_digits=20)),
                ('LTC', models.DecimalField(decimal_places=8, max_digits=20)),
                ('DASH', models.DecimalField(decimal_places=8, max_digits=20)),
                ('XMR', models.DecimalField(decimal_places=8, max_digits=20)),
                ('BTG', models.DecimalField(decimal_places=8, max_digits=20)),
                ('EOS', models.DecimalField(decimal_places=8, max_digits=20)),
                ('QTUM', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ETC', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ZEC', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'ordering': ['KRW'],
            },
        ),
    ]
